package com.hariharan.zerokey.sync

import com.hariharan.zerokey.core.crypto.CryptoEngine
import com.hariharan.zerokey.core.crypto.HmacEngine
import com.hariharan.zerokey.core.database.PasswordEntity
import com.hariharan.zerokey.core.common.PrivacyLogger
import kotlinx.serialization.json.Json
import kotlinx.serialization.builtins.ListSerializer

/**
 * VaultConflictResolver
 */
class VaultConflictResolver(
    private val cryptoEngine: CryptoEngine,
    private val hmacEngine: HmacEngine
) {
    companion object {
        private const val TAG = "VaultConflictResolver"
        private const val MERGE_WINDOW_MS = 5_000L
    }

    fun resolve(
        remote: EncryptedVaultBlob,
        local: EncryptedVaultBlob?,
        encryptionKey: ByteArray,
        hmacKey: ByteArray
    ): PullResult {
        if (local == null) {
            PrivacyLogger.i(TAG, "No local vault — accepting remote")
            return acceptRemote(remote, encryptionKey, hmacKey)
        }

        val timeDiff = Math.abs(remote.timestamp - local.timestamp)

        return when {
            remote.timestamp > local.timestamp -> {
                PrivacyLogger.i(TAG, "Remote snapshot wins (newer)")
                acceptRemote(remote, encryptionKey, hmacKey)
            }
            local.timestamp > remote.timestamp -> {
                PrivacyLogger.i(TAG, "Local snapshot wins (newer)")
                acceptRemote(local, encryptionKey, hmacKey)
            }
            timeDiff <= MERGE_WINDOW_MS -> {
                PrivacyLogger.i(TAG, "Timestamps tied — attempting merge")
                mergeVaults(remote, local, encryptionKey, hmacKey)
            }
            else -> acceptRemote(remote, encryptionKey, hmacKey)
        }
    }

    private fun acceptRemote(
        blob: EncryptedVaultBlob,
        encryptionKey: ByteArray,
        hmacKey: ByteArray
    ): PullResult {
        return try {
            val ivBytes = android.util.Base64.decode(blob.iv, android.util.Base64.NO_WRAP)
            val ciphertextBytes = android.util.Base64.decode(blob.encryptedVault, android.util.Base64.NO_WRAP)
            val combined = ivBytes + ciphertextBytes
            
            val decrypted = cryptoEngine.decryptAesGcm(combined, encryptionKey)
            PullResult.Success(String(decrypted, Charsets.UTF_8), blob.vaultVersion, blob.hmac)
        } catch (e: Exception) {
            PullResult.Failure("Decryption failed during conflict resolution")
        }
    }

    private fun mergeVaults(
        remote: EncryptedVaultBlob,
        local: EncryptedVaultBlob,
        encryptionKey: ByteArray,
        hmacKey: ByteArray
    ): PullResult {
        return try {
            val remoteIv = android.util.Base64.decode(remote.iv, android.util.Base64.NO_WRAP)
            val remoteCipher = android.util.Base64.decode(remote.encryptedVault, android.util.Base64.NO_WRAP)
            val remoteJson = String(cryptoEngine.decryptAesGcm(remoteIv + remoteCipher, encryptionKey), Charsets.UTF_8)

            val localIv = android.util.Base64.decode(local.iv, android.util.Base64.NO_WRAP)
            val localCipher = android.util.Base64.decode(local.encryptedVault, android.util.Base64.NO_WRAP)
            val localJson = String(cryptoEngine.decryptAesGcm(localIv + localCipher, encryptionKey), Charsets.UTF_8)

            val merged = mergeVaultJson(remoteJson, localJson)
            PrivacyLogger.i(TAG, "Field-level merge succeeded")
            PullResult.Success(merged, remote.vaultVersion, remote.hmac)
        } catch (e: Exception) {
            PrivacyLogger.e(TAG, "Merge failed: ${PrivacyLogger.sanitizeError(e.message)}")
            acceptRemote(remote, encryptionKey, hmacKey)
        }
    }

    fun mergeJson(remoteJson: String, localJson: String): String = mergeVaultJson(remoteJson, localJson)

    private fun mergeVaultJson(remoteJson: String, localJson: String): String {
        val json = Json { ignoreUnknownKeys = true }
        val remoteEntities = json.decodeFromString(ListSerializer(PasswordEntity.serializer()), remoteJson)
        val localEntities = json.decodeFromString(ListSerializer(PasswordEntity.serializer()), localJson)

        // SECURITY/CORRECTNESS: key by recordUid (a cross-device-stable UUID), not
        // the local autogenerated `id`. Two devices can assign the same `id` to
        // different records; merging by `id` would silently drop one of them.
        // Fall back to "id:<n>" only for legacy rows that have no recordUid.
        fun keyOf(e: PasswordEntity): String =
            if (e.recordUid.isNotBlank()) e.recordUid else "id:${e.id}"

        val merged = mutableMapOf<String, PasswordEntity>()
        localEntities.forEach { merged[keyOf(it)] = it }
        remoteEntities.forEach { remote ->
            val k = keyOf(remote)
            val existing = merged[k]
            if (existing == null || remote.lastModified > existing.lastModified) {
                merged[k] = remote
            }
        }
        return json.encodeToString(ListSerializer(PasswordEntity.serializer()), merged.values.toList())
    }
}
