package com.hariharan.zerokey.core.crypto

import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyInfo
import android.security.keystore.KeyProperties
import com.hariharan.zerokey.core.common.PrivacyLogger
import java.security.KeyStore
import java.security.SecureRandom
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.SecretKeyFactory
import javax.crypto.spec.GCMParameterSpec
import javax.inject.Inject
import javax.inject.Singleton

data class EncryptedData(val cipherText: ByteArray, val iv: ByteArray)

enum class KeySecurityLevel { STRONGBOX, TEE, SOFTWARE }

@Singleton
class EncryptionManager @Inject constructor() {
    companion object {
        private const val ANDROID_KEYSTORE = "AndroidKeyStore"
        private const val ROOT_KEY_ALIAS = "ZeroKey_Root_Hardware_Key"
        private const val AES_MODE = "AES/GCM/NoPadding"
        private const val IV_LENGTH = 12
        private const val AUTH_TAG_LENGTH = 128
    }

    private var initialized = false

    fun init() {
        if (initialized) return
        val keyStore = KeyStore.getInstance(ANDROID_KEYSTORE).apply { load(null) }
        if (!keyStore.containsAlias(ROOT_KEY_ALIAS)) {
            generateRootKey()
        }
        initialized = true
    }

    fun getKeySecurityLevel(): KeySecurityLevel {
        return try {
            val keyStore = KeyStore.getInstance(ANDROID_KEYSTORE).apply { load(null) }
            val key = keyStore.getKey(ROOT_KEY_ALIAS, null) as? SecretKey
                ?: return KeySecurityLevel.SOFTWARE
            val factory = SecretKeyFactory.getInstance(key.algorithm, ANDROID_KEYSTORE)
            val keyInfo = factory.getKeySpec(key, KeyInfo::class.java) as KeyInfo
            if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.S) {
                when (keyInfo.securityLevel) {
                    KeyProperties.SECURITY_LEVEL_STRONGBOX -> KeySecurityLevel.STRONGBOX
                    KeyProperties.SECURITY_LEVEL_TRUSTED_ENVIRONMENT -> KeySecurityLevel.TEE
                    else -> KeySecurityLevel.SOFTWARE
                }
            } else {
                @Suppress("DEPRECATION")
                if (keyInfo.isInsideSecureHardware) KeySecurityLevel.TEE else KeySecurityLevel.SOFTWARE
            }
        } catch (e: Exception) {
            PrivacyLogger.w("EncryptionManager", "Security level check failed: ${e.message}")
            KeySecurityLevel.SOFTWARE
        }
    }

    private fun generateRootKey() {
        try {
            val builder = KeyGenParameterSpec.Builder(
                ROOT_KEY_ALIAS,
                KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT
            )
                .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                .setKeySize(256)
                .setRandomizedEncryptionRequired(true)

            if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.P) {
                try { builder.setIsStrongBoxBacked(true) } catch (_: Exception) {}
            }

            val keyGen = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, ANDROID_KEYSTORE)
            keyGen.init(builder.build())
            keyGen.generateKey()
        } catch (e: Exception) {
            PrivacyLogger.e("EncryptionManager", "Root key generation failed: ${e.message}")
            throw e
        }
    }

    private fun getRootKey(): SecretKey {
        val keyStore = KeyStore.getInstance(ANDROID_KEYSTORE).apply { load(null) }
        return keyStore.getKey(ROOT_KEY_ALIAS, null) as SecretKey
    }

    /**
     * Encrypt with a software (non-Keystore) key. IV is generated by SecureRandom
     * and supplied via GCMParameterSpec so behavior is the same on every JCE provider.
     * NEVER use this with the Keystore root key — Keystore doesn't accept caller IVs.
     */
    fun encryptWithKey(data: ByteArray, key: SecretKey, aad: ByteArray? = null): EncryptedData {
        val cipher = Cipher.getInstance(AES_MODE)
        val iv = ByteArray(IV_LENGTH).also { SecureRandom().nextBytes(it) }
        cipher.init(Cipher.ENCRYPT_MODE, key, GCMParameterSpec(AUTH_TAG_LENGTH, iv))
        aad?.let { cipher.updateAAD(it) }
        return EncryptedData(cipher.doFinal(data), iv)
    }

    fun decryptWithKey(encryptedData: EncryptedData, key: SecretKey, aad: ByteArray? = null): ByteArray {
        val cipher = Cipher.getInstance(AES_MODE)
        val spec = GCMParameterSpec(AUTH_TAG_LENGTH, encryptedData.iv)
        cipher.init(Cipher.DECRYPT_MODE, key, spec)
        aad?.let { cipher.updateAAD(it) }
        return cipher.doFinal(encryptedData.cipherText)
    }

    /**
     * Encrypt with the Android Keystore root key. The Keystore provider generates
     * a fresh IV per call and does NOT accept a caller-supplied GCMParameterSpec
     * for ENCRYPT_MODE. We must call init(key) without a spec for this path only.
     */
    fun encryptWithRootKey(data: ByteArray, aad: ByteArray? = null): EncryptedData {
        val cipher = Cipher.getInstance(AES_MODE)
        cipher.init(Cipher.ENCRYPT_MODE, getRootKey())
        aad?.let { cipher.updateAAD(it) }
        val ciphertext = cipher.doFinal(data)
        return EncryptedData(ciphertext, cipher.iv)
    }

    fun decryptWithRootKey(encryptedData: EncryptedData, aad: ByteArray? = null): ByteArray {
        return decryptWithKey(encryptedData, getRootKey(), aad)
    }
}
